/*++

Module Name:
    ioctl.h

Abstract:
    Definições de códigos IOCTL para comunicação user-mode ↔ kernel-mode

--*/

#ifndef _KERNELSEC_IOCTL_H_
#define _KERNELSEC_IOCTL_H_

#pragma once

//
// Device type personalizado
//
#define FILE_DEVICE_KERNELSEC   0x8000

//
// Códigos IOCTL
//
#define IOCTL_KERNELSEC_GET_CONFIG \
    CTL_CODE(FILE_DEVICE_KERNELSEC, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_KERNELSEC_SET_CONFIG \
    CTL_CODE(FILE_DEVICE_KERNELSEC, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_KERNELSEC_GET_EVENTS \
    CTL_CODE(FILE_DEVICE_KERNELSEC, 0x802, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_KERNELSEC_ADD_WHITELIST \
    CTL_CODE(FILE_DEVICE_KERNELSEC, 0x803, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_KERNELSEC_REMOVE_WHITELIST \
    CTL_CODE(FILE_DEVICE_KERNELSEC, 0x804, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_KERNELSEC_GET_STATS \
    CTL_CODE(FILE_DEVICE_KERNELSEC, 0x805, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_KERNELSEC_RESET_BASELINE \
    CTL_CODE(FILE_DEVICE_KERNELSEC, 0x806, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_KERNELSEC_ENABLE_PROTECTION \
    CTL_CODE(FILE_DEVICE_KERNELSEC, 0x807, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_KERNELSEC_DISABLE_PROTECTION \
    CTL_CODE(FILE_DEVICE_KERNELSEC, 0x808, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_KERNELSEC_GET_VERSION \
    CTL_CODE(FILE_DEVICE_KERNELSEC, 0x809, METHOD_BUFFERED, FILE_READ_ACCESS)

//
// Nome do device
//
#define KERNELSEC_DEVICE_NAME      L"\\Device\\KernelSecDriver"
#define KERNELSEC_SYMLINK_NAME     L"\\??\\KernelSecDriver"
#define KERNELSEC_USERMODE_PATH    L"\\\\.\\KernelSecDriver"

#endif // _KERNELSEC_IOCTL_H_
